name: Auto Version Update

on:
  push:
    branches:
      - main

jobs:
  version-update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Update package version
        id: update_version
        run: |
          # 讀取 package.json 檔案
          VERSION=$(grep '"version":' package.json | cut -d\" -f4)

          # 分割版本號
          IFS='.' read -r major minor patch <<< "$VERSION"

          # 增加修訂號 (patch)
          new_patch=$((patch + 1))
          NEW_VERSION="$major.$minor.$new_patch"

          # 更新 package.json
          sed -i "s/\"version\": \"$VERSION\"/\"version\": \"$NEW_VERSION\"/" package.json

          # 輸出新版本號
          echo "::set-output name=new_version::$NEW_VERSION"

          # 提交更改
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add package.json
          git commit -m "Auto-increment version to $NEW_VERSION [skip ci]"
          git push

      - name: Display new version
        run: echo "New version is ${{ steps.update_version.outputs.new_version }}"
